version: '3.8'

services:
  db:
    container_name: fuchibol_db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: fuchibol_user
      POSTGRES_PASSWORD: fuchibol_password
      POSTGRES_DB: fuchibol_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: fuchibol_redis
    image: redis:7-alpine
    restart: always
    ports:
      - "6376:6379"

  srs:
    container_name: fuchibol_srs
    build:
      context: ./srs
    restart: always
    command: ./objs/srs -c conf/srs.conf
    ports:
      - "1936:1935"
      - "1986:1985"
      - "8086:8080"
      - "21116:21116/udp"
    volumes:
      - srs_hls:/usr/local/srs/objs/nginx/html
    depends_on:
      - backend

  backend:
    container_name: fuchibol_backend
    build:
      context: ./backend-go
    restart: always
    command: ./api_server
    volumes:
      - srs_hls:/app/srs_hls
      - uploads:/app/uploads
      - ./hls_offline:/app/hls_offline
    ports:
      - "8005:8000"
    environment:
      - DATABASE_URL=postgresql://fuchibol_user:fuchibol_password@db:5432/fuchibol_db
      - REDIS_URL=redis://redis:6379/0
      - SECRET_KEY=fuchibol_super_secret_key_change_me_in_prod
      - JWT_ALGORITHM=HS256
      - HLS_BASE_URL=/hls
    depends_on:
      - db
      - redis

  celery:
    container_name: fuchibol_celery
    build:
      context: ./backend-go
    restart: always
    command: ./worker_server
    volumes:
      - srs_hls:/app/srs_hls
      - ./hls_offline:/app/hls_offline
    environment:
      - DATABASE_URL=postgresql://fuchibol_user:fuchibol_password@db:5432/fuchibol_db
      - REDIS_URL=redis://redis:6379/0
      - HLS_BASE_URL=/hls
    depends_on:
      - db
      - redis

  nginx:
    container_name: fuchibol_nginx
    build:
      context: ./nginx
    restart: always
    ports:
      - "8085:80"
    volumes:
      - srs_hls:/usr/share/nginx/html/hls
      - uploads:/usr/share/nginx/html/uploads
      - ./hls_offline:/usr/share/nginx/html/offline
    depends_on:
      - backend
      - frontend

  frontend:
    container_name: fuchibol_frontend
    build:
      context: ./frontend
    restart: always
    # No ports exposed directly, only through nginx container


volumes:
  pgdata:
  srs_hls:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=512m,mode=1777"
  uploads:
