"""add_agenda_events

Revision ID: 5da8093e48ed
Revises: e9e968015c13
Create Date: 2026-06-09 15:41:05.917601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da8093e48ed'
down_revision: Union[str, None] = 'e9e968015c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('agenda_events', sa.String(), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'agenda_events')
    # ### end Alembic commands ###
