"""add_whatsapp_link

Revision ID: d043c7dfdba8
Revises: 5da8093e48ed
Create Date: 2026-06-09 18:03:32.066170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd043c7dfdba8'
down_revision: Union[str, None] = '5da8093e48ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('whatsapp_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'whatsapp_link')
    # ### end Alembic commands ###
