"""Add IPTV fields

Revision ID: e9e968015c13
Revises: 000000000001
Create Date: 2026-06-08 04:04:40.298345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e968015c13'
down_revision: Union[str, None] = '000000000001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('iptv_urls', sa.String(), nullable=False, server_default='[]'))
    op.add_column('channels', sa.Column('active_iptv_url', sa.String(), nullable=True))
    op.add_column('channels', sa.Column('iptv_enabled', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('channels', 'iptv_enabled')
    op.drop_column('channels', 'active_iptv_url')
    op.drop_column('channels', 'iptv_urls')
    # ### end Alembic commands ###
